"""Generates markets_rest.yaml (REST sensors) and dashboards/markets.yaml for HA.
Crypto via CoinGecko (no key), stocks/indices/FX via Yahoo's v8 chart endpoint (no key)."""
import json, sys

CRYPTO = [  # (coingecko id, key, name, icon)
    ("bitcoin", "btc", "Bitcoin", "mdi:bitcoin"),
    ("ethereum", "eth", "Ethereum", "mdi:ethereum"),
    ("solana", "sol", "Solana", "mdi:alpha-s-circle"),
]
INDICES = [  # (yahoo symbol, key, name, unit)
    ("^NSEI", "nifty50", "NIFTY 50", "pts"),
    ("^BSESN", "sensex", "SENSEX", "pts"),
    ("^GSPC", "sp500", "S&P 500", "pts"),
    ("USDINR=X", "usdinr", "USD / INR", "₹"),
]
STOCKS = [
    ("RELIANCE.NS", "reliance", "Reliance", "₹"),
    ("TCS.NS", "tcs", "TCS", "₹"),
    ("INFY.NS", "infosys", "Infosys", "₹"),
    ("HDFCBANK.NS", "hdfcbank", "HDFC Bank", "₹"),
]
UA = {"User-Agent": "Mozilla/5.0 (HomeAssistant markets dashboard)"}

rest = []
ids = ",".join(c[0] for c in CRYPTO)
sensors = []
for cid, key, name, icon in CRYPTO:
    sensors.append({
        "name": f"{name} price", "unique_id": f"markets_{key}_price", "icon": icon,
        "value_template": f"{{{{ value_json['{cid}']['inr'] }}}}",
        "unit_of_measurement": "₹", "state_class": "measurement",
    })
    sensors.append({
        "name": f"{name} change 24h", "unique_id": f"markets_{key}_change", "icon": "mdi:percent",
        "value_template": f"{{{{ value_json['{cid}']['inr_24h_change'] | round(2) }}}}",
        "unit_of_measurement": "%", "state_class": "measurement",
    })
rest.append({
    "resource": "https://api.coingecko.com/api/v3/simple/price?ids="
                f"{ids}&vs_currencies=inr&include_24hr_change=true",
    "scan_interval": 180, "timeout": 20, "headers": UA, "sensor": sensors,
})

META = "value_json.chart.result[0].meta"
for sym, key, name, unit in INDICES + STOCKS:
    rest.append({
        "resource": f"https://query1.finance.yahoo.com/v8/finance/chart/{sym}?interval=1d&range=1d",
        "scan_interval": 300, "timeout": 20, "headers": UA,
        "sensor": [
            {"name": f"{name} price", "unique_id": f"markets_{key}_price", "icon": "mdi:chart-line",
             "value_template": f"{{{{ {META}.regularMarketPrice }}}}",
             "unit_of_measurement": unit, "state_class": "measurement"},
            {"name": f"{name} change", "unique_id": f"markets_{key}_change", "icon": "mdi:percent",
             # day change vs previous close (computed, so it works even if Yahoo drops the % field)
             "value_template": f"{{% set m = {META} %}}"
                               "{{ ((m.regularMarketPrice - m.chartPreviousClose) / m.chartPreviousClose * 100) | round(2) }}",
             "unit_of_measurement": "%", "state_class": "measurement"},
        ],
    })


def eid(name, suffix):
    slug = "".join(ch if ch.isalnum() else "_" for ch in name.lower())
    while "__" in slug:
        slug = slug.replace("__", "_")
    return f"sensor.{slug.strip('_')}_{suffix}"


def table(title, rows, change_suffix):
    lines = [f"| {title} | Price | Change |", "|:--|--:|--:|"]
    for name, unit in rows:
        p, c = eid(name, "price"), eid(name, change_suffix)
        cur = "₹" if unit == "₹" else ""
        lines.append(
            f"| **{name}** | {cur}{{{{ '{{:,.2f}}'.format(states('{p}') | float(0)) }}}} | "
            f"{{% set c = states('{c}') | float(0) %}}"
            f"<font color=\"{{{{ '#21c45d' if c >= 0 else '#ef4444' }}}}\">"
            f"{{{{ '▲' if c >= 0 else '▼' }}}} {{{{ '%+.2f' | format(c) }}}}%</font> |")
    return "\n".join(lines)


def section(title, rows, change_suffix, hours):
    cards = [{"type": "heading", "heading": title},
             {"type": "markdown", "content": table(title, rows, change_suffix)}]
    for name, unit in rows:
        cards.append({"type": "sensor", "entity": eid(name, "price"), "name": name,
                      "graph": "line", "hours_to_show": hours, "detail": 2,
                      "grid_options": {"columns": 6}})
    return {"type": "grid", "cards": cards}


dash = {
    "title": "Markets",
    "views": [{
        "title": "Markets", "path": "markets", "icon": "mdi:finance", "type": "sections",
        "max_columns": 3,
        "sections": [
            section("Crypto (INR)", [(c[2], "₹") for c in CRYPTO], "change_24h", 24),
            section("Indices & FX", [(i[2], i[3]) for i in INDICES], "change", 48),
            section("Stocks (NSE)", [(s[2], s[3]) for s in STOCKS], "change", 48),
        ],
    }],
}

HEADER = ("# Market prices for the Markets dashboard. Generated by gen_markets.py (claude_work repo,\n"
          "# haos-pi5/). Crypto: CoinGecko free API. Stocks/indices/FX: Yahoo v8 chart. No API keys.\n")
out = sys.argv[1]
# JSON is valid YAML; dump with yaml if available for readability
import yaml


class Dumper(yaml.SafeDumper):
    def ignore_aliases(self, data):
        return True


def _str(d, s):
    return d.represent_scalar("tag:yaml.org,2002:str", s, style="|" if "\n" in s else None)


Dumper.add_representer(str, _str)
dump = lambda d: yaml.dump(d, Dumper=Dumper, sort_keys=False, allow_unicode=True, width=1000)
open(f"{out}/markets_rest.yaml", "w", encoding="utf-8", newline="\n").write(HEADER + dump(rest))
open(f"{out}/markets_dashboard.yaml", "w", encoding="utf-8", newline="\n").write(
    "# Markets dashboard (YAML mode). Generated by gen_markets.py.\n" + dump(dash))
print("ok")
