#!/usr/bin/env bash
# Snapshot the HAOS Pi 5's hand-maintained config into this folder (secrets stripped on the Pi).
# Run from Git Bash on the Windows PC:  bash haos-pi5/pull_backup.sh
# Needs the `haos` SSH alias (see CLAUDE.md -> "How to reach it").
set -euo pipefail
cd "$(dirname "$0")"
mkdir -p config/themes host

R() { ssh -o BatchMode=yes haos "$@"; }

echo "config files"
for f in configuration.yaml automations.yaml scripts.yaml scenes.yaml; do
  R "sudo -n cat /homeassistant/$f" > "config/$f"
done
for t in $(R "sudo -n ls /homeassistant/themes"); do
  R "sudo -n cat /homeassistant/themes/$t" > "config/themes/$t"
done

echo "host-level tweaks"
R "sudo -n docker run --rm -v /mnt/boot:/b:ro alpine cat /b/config.txt" > host/boot-config.txt
R "sudo -n docker run --rm -v /mnt/overlay/etc/modules-load.d:/m:ro alpine sh -c 'for f in /m/*; do echo \"# \$f\"; cat \"\$f\"; done'" > host/modules-load.d.txt

# Add-on options.json files are deliberately NOT pulled: they hold the kiosk's HA login and the SSH
# add-on password. Their non-secret settings are written down by hand in RESTORE.md instead.

echo "inventory"
{
  echo "# HAOS Pi 5 inventory (generated by pull_backup.sh)"
  echo
  echo "## Versions"
  echo '```'
  echo "HA Core: $(R 'sudo -n cat /homeassistant/.HA_VERSION')"
  R "sudo -n docker run --rm -v /etc/os-release:/o:ro alpine grep -E '^(NAME|VERSION)=' /o"
  echo '```'
  echo
  echo "## Running containers (add-ons = app_*)"
  echo '```'
  R "sudo -n docker ps --format '{{.Names}}  {{.Image}}' | sort"
  echo '```'
  echo
  echo "## Integrations (config entries; titles omitted - some contain account emails)"
  echo '```'
  R "sudo -n docker exec homeassistant python3 -c \"import json,collections;d=json.load(open('/config/.storage/core.config_entries'))['data']['entries'];c=collections.Counter(e['domain'] for e in d);[print(k, 'x'+str(v) if v>1 else '') for k,v in sorted(c.items())]\""
  echo '```'
  echo
  echo "## HACS repositories installed"
  echo '```'
  R "sudo -n docker exec homeassistant python3 -c \"import json;d=json.load(open('/config/.storage/hacs.repositories'))['data'];[print(v.get('full_name'), v.get('version_installed') or '') for v in d.values() if v.get('installed')]\" | sort"
  echo '```'
  echo
  echo "## custom_components on disk"
  echo '```'
  R "sudo -n docker exec homeassistant sh -c 'for m in /config/custom_components/*/manifest.json; do python3 -c \"import json,sys;j=json.load(open(sys.argv[1]));print(j.get(\\\"domain\\\"), j.get(\\\"version\\\"))\" \$m; done'"
  echo '```'
  echo
  echo "## HA full backups stored on the Pi (contain secrets - never commit these)"
  echo '```'
  R "sudo -n docker run --rm -v /mnt/data/supervisor/backup:/bk:ro alpine ls -la /bk"
  echo '```'
} > INVENTORY.md

echo "sanity check for leaked secrets"
if grep -rniE '"(ha_)?password"|bearer|eyJhbGci' config host INVENTORY.md; then
  echo "!!! possible secret found above - do not commit" >&2
  exit 1
fi
echo "done"
